services:
  tourguide:
    # CORRECTION 1: Utiliser l'image construite au lieu de build
    image: tourguide-app:${CONTAINER_TAG:-latest}
    container_name: tourguide-app-${BRANCH_NAME:-local}-${BUILD_NUMBER:-dev}
    ports:
      # CORRECTION 2: Utiliser SERVER_PORT (défini dans .env) au lieu d'INTERNAL_PORT
      - "${HTTP_PORT:-8091}:${SERVER_PORT:-8091}"
    environment:
      - JAVA_OPTS=${JAVA_OPTS:-"-Xmx512m -Xms256m -XX:+UseContainerSupport"}
      # CORRECTION 3: Utiliser SERVER_PORT cohérent
      - SERVER_PORT=${SERVER_PORT:-8091}
      # CORRECTION 4: Utiliser ENV_NAME au lieu de SPRING_PROFILES_ACTIVE hardcodé
      - SPRING_PROFILES_ACTIVE=${ENV_NAME:-uat}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # CORRECTION 5: Management sur le même port
      - MANAGEMENT_SERVER_PORT=${SERVER_PORT:-8091}
      - BRANCH_NAME=${BRANCH_NAME:-develop}
      - BUILD_NUMBER=${BUILD_NUMBER:-dev}
      # AJOUT: Variables supplémentaires pour l'application
      - APP_NAME=${APP_NAME:-TourGuide}
      - APP_VERSION=${APP_VERSION:-0.0.1-SNAPSHOT}
      - APP_ENVIRONMENT=${ENV_NAME:-uat}
    networks:
      - tourguide-network
    restart: unless-stopped
    volumes:
      - app-logs:/opt/app/logs
      - /tmp:/tmp
    healthcheck:
      # CORRECTION 6: Utiliser SERVER_PORT au lieu d'INTERNAL_PORT
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-8091}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tourguide-network:
    driver: bridge
    name: tourguide-network

volumes:
  app-logs:
    driver: local