services:
  tourguide:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2025-07-31T11:00:00Z}
        VCS_REF: ${VCS_REF:-unknown}
        BUILD_NUMBER: ${BUILD_NUMBER:-dev}
    container_name: tourguide-app-${BRANCH_NAME:-local}-${BUILD_NUMBER:-dev}
    ports:
      # CORRECTION: Mapper vers le port correct selon l'environnement
      - "${HTTP_PORT:-8090}:${INTERNAL_PORT:-8080}"
    environment:
      - JAVA_OPTS=${JAVA_OPTS:-"-Xmx512m -Xms256m -XX:+UseContainerSupport"}
      # CORRECTION: Utiliser le port dynamique selon l'environnement
      - SERVER_PORT=${INTERNAL_PORT:-8080}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # AJOUT: Variables d'environnement supplémentaires
      - MANAGEMENT_SERVER_PORT=${INTERNAL_PORT:-8080}
      - BRANCH_NAME=${BRANCH_NAME:-develop}
      - BUILD_NUMBER=${BUILD_NUMBER:-dev}
    networks:
      - tourguide-network
    restart: unless-stopped
    volumes:
      # AJOUT: Volume pour les logs
      - app-logs:/opt/app/logs
      - /tmp:/tmp
    healthcheck:
      # CORRECTION: Utiliser le port dynamique pour le health check
      test: ["CMD", "curl", "-f", "http://localhost:${INTERNAL_PORT:-8080}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tourguide-network:
    driver: bridge
    name: tourguide-network

volumes:
  app-logs:
    driver: local