services:
  tourguide:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-2025-07-31T11:00:00Z}
        VCS_REF: ${VCS_REF:-unknown}
        BUILD_NUMBER: ${BUILD_NUMBER:-dev}
    container_name: tourguide-app
    ports:
      - "${HTTP_PORT:-8081}:8080"  # Port dynamique basé sur la branche
    environment:
      - JAVA_OPTS=${JAVA_OPTS:-"-Xmx512m -Xms256m -XX:+UseContainerSupport"}
      - SERVER_PORT=8080
      - SPRING_ACTIVE_PROFILES=${SPRING_ACTIVE_PROFILES:-prod}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - tourguide-network
    restart: unless-stopped

    # Health check au niveau Docker Compose
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    # Limites de ressources
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

    # Logs configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tourguide-network:
    driver: bridge
    name: ${NETWORK_NAME:-tourguide-network}

# Volumes pour persistance (si nécessaire)
volumes:
  app-logs:
    driver: local