services:
  tourguide:
    # Use the constructed image
    image: tourguide-app:${CONTAINER_TAG:-latest}
    container_name: tourguide-app-${BRANCH_NAME:-local}-${BUILD_NUMBER:-dev}
    ports:
      # Use SERVER_PORT (defined in .env) instead of INTERNAL_PORT
      - "${HTTP_PORT:-8091}:${SERVER_PORT:-8091}"
    environment:
      - JAVA_OPTS=${JAVA_OPTS:-"-Xmx512m -Xms256m -XX:+UseContainerSupport"}
      # USE PROD SERVER_PORT
      - SERVER_PORT=${SERVER_PORT:-8091}
      # USE ENV_NAME
      - SPRING_PROFILES_ACTIVE=${ENV_NAME:-uat}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # Management on the same port
      - MANAGEMENT_SERVER_PORT=${SERVER_PORT:-8091}
      - BRANCH_NAME=${BRANCH_NAME:-develop}
      - BUILD_NUMBER=${BUILD_NUMBER:-dev}
      # variables for the application
      - APP_NAME=${APP_NAME:-TourGuide}
      - APP_VERSION=${APP_VERSION:-0.0.1-SNAPSHOT}
      - APP_ENVIRONMENT=${ENV_NAME:-uat}
    networks:
      - tourguide-network
    restart: unless-stopped
    volumes:
      - app-logs:/opt/app/logs
      - /tmp:/tmp
    healthcheck:
      # USE SERVER_PORT
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-8091}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tourguide-network:
    driver: bridge
    name: tourguide-network

volumes:
  app-logs:
    driver: local