server:
  port: 8080  # Port interne du conteneur

logging:
  level:
    com:
      openclassrooms:
        tourguide: DEBUG
    org:
      springframework: INFO
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always