server:
  port: ${SERVER_PORT:8090} #Use the environment variable

logging:
  level:
    com:
      openclassrooms:
        tourguide: DEBUG
    org:
      springframework: DEBUG
    root: INFO

management:
  server:
    port: ${SERVER_PORT:8090} # Same port as the application
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always